# Generated by Django 5.1.5 on 2025-03-03 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='conuntry',
            new_name='country',
        ),
    ]
