# Generated by Django 5.1.5 on 2025-03-03 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0002_rename_conuntry_userprofile_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='client',
            new_name='user',
        ),
    ]
