# Generated by Django 5.1.5 on 2025-02-27 00:37

import django.utils.timezone
import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_groupchatroom_room_code_privatechatroom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupchatroom',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='edited_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='message_type',
            field=models.CharField(blank=True, choices=[('text', 'Text Message'), ('file', 'File Upload'), ('system', 'System Message')], max_length=15),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='read_by',
            field=models.ManyToManyField(related_name='receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupchatroom',
            name='room_code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='privatechatroom',
            name='room_code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=15, unique=True),
        ),
    ]
