# Generated by Django 5.1.5 on 2025-03-13 13:14

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_groupchatroom_room_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatroom',
            name='room_code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='message_type',
            field=models.CharField(blank=True, choices=[('text', 'Text Message'), ('file', 'File Upload'), ('system', 'System Message')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='privatechatroom',
            name='room_code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=15, unique=True),
        ),
    ]
